version: "3.8"

services:
  postgres:
    image: postgres:11-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 3s
      timeout: 2s
      retries: 10

  nginx:
    build: ./nginx
    depends_on:
      - service
    volumes:
      - ./static:/static/
      - ./media:/media/
    ports:
      - "80:80"
      - "443:443"

  service:
    build:
      context: .
    command: python src/main.py
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - PYTHONPATH=/app
      - POSTGRES_DSN=postgres://postgres:postgres@postgres/postgres
      - authjwt_secret_key=${authjwt_secret_key}
      - REMOTE_SERVER_HOST=${REMOTE_SERVER_HOST}
    ports:
      - "8000:8000"


volumes:
  postgres-data: